### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by nc6** [4e6/stack2nix#15]
`stack2nix` has already been "claimed" on hackage by https://hackage.haskell.org/package/stack2nix. I think this is the better tool, but probably easier to get a new name than suffer the confusion?

**Comment by 4e6** [comment]
Yes, I'm aware of what IOHK guys are doing. This piece of software is trying to solve the same problem but uses a different approach. Instead of parsing Stack output, it generates Stackage snapshot and applies some additional overrides on top of it. I believe this is a more robust method.

Currently, I'm refactoring everything into a single `stackage2nix` executable. This would be the new name, and I am interested to publish it eventually to Hackage when it matures. Stay tuned!
